@startuml
!include skinparam.puml
!include MultiGraphADT.puml

+class BostonMetro{
    -String currentStation
    -String destination
    -ArrayList route
    +getStation()
    +getDestination()
    +setDestination()
    +getRoute()
}

+class MetroMapParser{
    +generateGraphFromFile()
}

+class Station{
    -int id
    -String station
    -String metroLine
    +getID()
    +getName()
    +getMetroLine()
}

BostonMetro --> MetroMapParser
BostonMetro o-- Station
MetroMapParser --> Station
BostonMetro ..|> MultiGraph : <<extends>>
MultiGraph *-- Edge

@enduml