@startuml
!include skinparam.puml
!include MultiGraphADT.puml
!include GUI.puml

+class BostonMetro{
    -ArrayList<String> stationList
    -Station currentStation;
    -Station destination
    -ArrayList<String> route
    -MetroMapParser mmp
    -DirectedGraph<Station, Track<Station>> graph
    +Station getStation()
    +void setHomeStation(Station name)
    +void setDestination(Station dest)
    +Station getDestination()
    +List<String> getStations()
    +List<Station> getRoute()
    +Station lookupStation(String name)
}

+class MetroMapParser{
    -void usage()
    +DirectedGraph<Station, Track<Station>> generateGraphFromFile()
}

+class Station{
    -int id
    -String name
    -String metroLine
    +int getID()
    +String getName()
    +String getMetroLine()
    +void setMetroLine(String line)
    +void setID(int id)
    +void setName(String name)
    +boolean equals(Object obj)
    +int hashCode()
}

+class Track<V> implements DirectedEdge{
    -String lineColour
    -V sourceVertex
    -V targetVertex
    +String getLineColour()
    +V getSourceVertex()
    +V getTargetVertex()
}

App --> BostonMetro
BostonMetro --> MetroMapParser
BostonMetro o-- Station
MetroMapParser --> Station
MetroMapParser --> Track
MetroMapParser --* MultiGraph
MultiGraph --> Track

@enduml