@startuml
!include skinparam.puml

+interface DirectedGraph extends DirectedEdge{
    -String NOVERTEXTERROR
    +addVertex(V vertex)
    +addVertices(Collection<extends v> vertices)
    +addEdge(E edge)
    +addEdges(Collection<extends E> edges)
    +removeVertex(V vertex)
    +removeEdge(V sourceVertex, V targetVertex)
    +removeEdge(E edge)
    +isAdjacent(V sourceVertex, V targetVertex)
    +isEmpty()
    +getNumVertices()
    +getNumEdges()
    +getAdjacent()
    +getVertices()
}

+interface DirectedEdge{
    +getSourceVertex()
    +getTargetVertex()
}

+class MultiGraph extends DirectedEdge implements DirectedGraph {
    -ArrayList<Vertex> Vertices
    -ArrayList<Edge> edges
    +addVertex(V vertex)
    +addVertices(Collection<extends v> vertices)
    +addEdge(E edge)
    +addEdges(Collection<extends E> edges)
    +removeVertex(V vertex)
    +removeEdge(V sourceVertex, V targetVertex)
    +removeEdge(E edge)
    +isAdjacent(V sourceVertex, V targetVertex)
    +isEmpty()
    +getNumVertices()
    +getNumEdges()
    +getAdjacent()
    +getVertices()
}

@enduml