@startuml
!include skinparam.puml


+class Edge {
    +getStartVertex()
    +setStartVertex()
    +getEndVertex()
    +setEndVertex()
}
note bottom: If we did weights \ncould they be 1 for same\n line and 2 for switching lines?

+interface GraphADT {
    +getVertices()
    +getEdges()
    +hasEdge(Vertex startV, Vertex endV)
    +isEmpty()
    +getNumVertices()
    +getNumEdges()
    +addVertex(Vertex v)
    +addEdge(Edge edge)
}

+class MultiGraph implements GraphADT {
    -ArrayList<Vertex> Vertices
    -ArrayList<Edge> edges
    +getVertices()
    +getEdges()
    +hasEdge(Vertex startV, Vertex endV)
    +isEmpty()
    +getNumVertices()
    +getNumEdges()
    +addVertex(Vertex v)
    +addEdge(Edge edge)
}

@enduml